repos:
  - repo: local
    hooks:
    - id: formatting
      name: format
      description: Run cargo fmt on files included in the commit. rustfmt should be installed before-hand.
      entry: |
          mise run format
      types: [file, rust]
      language: system
    - id: linting
      name: lint
      description: Run cargo clippy on files included in the commit. clippy should be installed before-hand.
      entry: |
          mise run lint
      pass_filenames: false
      types: [file, rust]
      language: system
    - id: audit
      name: audit
      description: Run cargo deny dependencies.
      entry: |
          mise run audit
      pass_filenames: false
      types: [file, rust]
      language: system
    - id: machete
      name: machete
      description: Run cargo machete on dependencies.
      entry: |
          mise run machete
      pass_filenames: false
      types: [file, rust]
      language: system
    - id: test
      name: test
      description: Run cargo test.
      entry: |
          mise run test
      pass_filenames: false
      types: [file, rust]
      language: system